name: ci

on:
  push:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  test:
    defaults:
      run:
        working-directory: go/src/github.com/microservices-demo/catalogue
    runs-on: ubuntu-latest
    env:
      GROUP: europe-west3-docker.pkg.dev/cnpe-blue/sockshop
      COMMIT: ${{ github.sha }}
      REPO: catalogue
      GO_VERSION: 1.7.5
      GOPATH: /home/runner/work/catalogue/catalogue/go

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/microservices-demo/catalogue

      - name: Submit Coveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverage.out -service=github

      - name: Build catalogue image
        uses: docker/build-push-action@v1
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
          push: false
          dockerfile: go/src/github.com/microservices-demo/catalogue/docker/catalogue/Dockerfile
          path: go/src/github.com/microservices-demo/catalogue
          repository: ${{ env.GROUP }}/${{ env.REPO }}
          tag_with_ref: true
          tag_with_sha: true

      - name: Build catalogue-db image
        uses: docker/build-push-action@v1
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
          push: false
          dockerfile: go/src/github.com/microservices-demo/catalogue/docker/catalogue-db/Dockerfile
          path: go/src/github.com/microservices-demo/catalogue/docker/catalogue-db
          repository: ${{ env.GROUP }}/${{ env.REPO }}
          tag_with_ref: true
          tag_with_sha: true
          
      # Push to GAR
      - name: Login to GAR
        uses: docker/login-action@v1
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
          registry: europe-west3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Push to GAR
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        run: docker push ${{ env.GROUP }}/${{ env.REPO }} --all-tags  
